name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia Ã  meia-noite
  workflow_dispatch: # permite rodar manualmente
  push: # tambÃ©m roda quando vocÃª fizer push

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositÃ³rio
        uses: actions/checkout@v3

      - name: Gerar a cobrinha ğŸ
        uses: Platane/snk@v3
        with:
          github_user_name: WagnerK4uan
          outputs: |
            ./output/github-contribution-grid-snake-dark.svg
          color_snake: "#ffffff"
          color_dots: "#0e4429,#006d32,#26a641,#39d353,#ffffff" # do mais escuro para o mais claro

      - name: Commit e push da cobrinha
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "ğŸ Atualizando cobrinha de contribuiÃ§Ãµes"
          add: "output/*.svg"
